Homework dz6
Natanefa/automation-courses-nefodova pull request #4
Opened 2020-09-05 15:41 UTC by Natanefa

Задачи к ДЗ 6. Лекция 4 Java Basics. Loops Arrays

2020-09-05 22:28 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task11.java
> +        int tmp = 0;
interesting solution ))

2020-09-05 22:32 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task13.java
> +        int mult = 0;
set variable mult  to 1, because  **mult = mult * array[i];** will be always **0**

2020-09-05 22:35 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task4.java
> +//        int evenSum = 0;
delete commented code please

2020-09-05 22:39 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task8.java
> +//                System.out.println(i);
delete

2020-09-05 22:39 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task8.java
> +//            System.out.println(i +  " " + myArray[i]);
delete

2020-09-05 22:42 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task8.java
> +            if (i >= start && i <= stop){
looks like wrong condition, should be 
            **_if (i >= start && i <= stop){_**

with current condition missed 1 element 
![image](https://user-images.githubusercontent.com/19190298/92314569-0f814980-efe2-11ea-8e2d-ed5e8dd5775f.png)

with condition         ###      **if (i >= start && i < stop){**

![image](https://user-images.githubusercontent.com/19190298/92314573-2aec5480-efe2-11ea-86b9-c74164cf273f.png)

2020-09-05 22:43 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task9.java
> +//            System.out.println(myArray[i]);
delete

2020-09-05 22:44 UTC, schvets requested changes
please provide small fixes. 
Awesome job !!!

2020-09-10 18:41 UTC, Natanefa commented on src/main/java/homeworks_dz6/hw_task8.java
> +            if (i >= start && i <= stop){
I don't understand, where is a problem

2020-09-11 17:07 UTC, schvets commented on src/main/java/homeworks_dz6/hw_task8.java
> +            if (i >= start && i <= stop){
just change condition from   **if (i >= start && i <= stop)** to   **if (i >= start && i < stop)**     
After that changes should work properly

2020-09-11 17:08 UTC, merged